name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build_sbt_0_13:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: sbt test and packagedArtifacts for sbt 0.13.x
      run: |
        sbt "++2.10.4" "^^0.13.17" test packagedArtifacts
    - name: sbt Publish for sbt 0.13.x
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
      run: |
        echo 'sbt "++2.10.4" "^^0.13.17" clean publish"'
        sbt "++2.10.4" "^^0.13.17" clean publish

  build_sbt_1_0:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: sbt test and packagedArtifacts for sbt 1.x
      run: |
        sbt "++2.12.10" "^^1.1.6" test packagedArtifacts
    - name: sbt Publish for sbt 1.x
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
      run: |
        echo 'sbt "++2.12.10" "^^1.1.6" clean publish"'
        sbt "++2.12.10" "^^1.1.6" clean publish
