name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build_sbt_1_0:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: sbt test and packagedArtifacts for sbt 1.x
      run: |
        sbt test packagedArtifacts
    - name: sbt Publish for sbt 1.x
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
      run: |
        echo 'sbt clean publish"'
        sbt clean publish
